use `high_mountains`;


-- user
INSERT INTO `user` (`id`,`imageUrl`,`name`,`firstName`,`middleName`,`lastName`,`userType`,`shopType`,`gender`,`dob`,`email`,`phone`,`password`,`lastLogin`,`status`,`city`,`state`,`country`,`address`,`deviceToken`,`isLoggedIn`,`onlineStatus`) VALUES (1,'profile.png','Default User',NULL,NULL,NULL,'2',NULL,'male',NULL,'user@edeals.com',NULL,'1234',NULL,NULL,NULL,NULL,NULL,NULL,'cy3IxpKsXEw:APA91bHql_y-m3a-0Mzv3yoPTb_1QBHJHl7i6Opv4nAboyDI1Myv67TinMks8e_5mg3WxakVUf-vShfkhRGsA_eCJz5g917DzpS5AWA8RbBpr39wALN-RJH1Ya-0EhawQDAvPZh63_Dn',1,0);
INSERT INTO `user` (`id`,`imageUrl`,`name`,`firstName`,`middleName`,`lastName`,`userType`,`shopType`,`gender`,`dob`,`email`,`phone`,`password`,`lastLogin`,`status`,`city`,`state`,`country`,`address`,`deviceToken`,`isLoggedIn`,`onlineStatus`) VALUES (2,NULL,'Shivank Sharma',NULL,NULL,NULL,'1',NULL,'male',NULL,'shivank@edeals.com',NULL,'1234',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO `user` (`id`,`imageUrl`,`name`,`firstName`,`middleName`,`lastName`,`userType`,`shopType`,`gender`,`dob`,`email`,`phone`,`password`,`lastLogin`,`status`,`city`,`state`,`country`,`address`,`deviceToken`,`isLoggedIn`,`onlineStatus`) VALUES (3,NULL,'Utkarsh Raj',NULL,NULL,NULL,'2',NULL,'male',NULL,'utkarsh@edeals.com',NULL,'1234',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO `user` (`id`,`imageUrl`,`name`,`firstName`,`middleName`,`lastName`,`userType`,`shopType`,`gender`,`dob`,`email`,`phone`,`password`,`lastLogin`,`status`,`city`,`state`,`country`,`address`,`deviceToken`,`isLoggedIn`,`onlineStatus`) VALUES (4,NULL,'Manish Bhan',NULL,NULL,NULL,'2',NULL,'male',NULL,'manish@edeals.com',NULL,'1234',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO `user` (`id`,`imageUrl`,`name`,`firstName`,`middleName`,`lastName`,`userType`,`shopType`,`gender`,`dob`,`email`,`phone`,`password`,`lastLogin`,`status`,`city`,`state`,`country`,`address`,`deviceToken`,`isLoggedIn`,`onlineStatus`) VALUES (5,NULL,'Himanshu Sharma',NULL,NULL,NULL,'1',NULL,'male',NULL,'himanshu@edeals.com',NULL,'1234',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
