export interface UserModel {
    id?: number;
    imageUrl?: string;
    name?: string;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    userName?: string;
    referalCode?: string;
    email?: string;
    gender?: string;
    dob?: string;
    phone?: string;
    password?: string;
    lastLogin?: string;
    city?: string;
    state?: string;
    country?: string;
    address?: string;
    about?: string;
    deviceToken?: string;
    status?: string;
    isLoggedIn?: number;
    onlineStatus?: number;
    adhar_number?: number;
    following?: number;
    followers?: number;
    level?: number;
}
